#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
		echo 'AMH-ModuleName: phpMyAdmin-4.0.7';
		echo 'AMH-ModuleDescription: 最新版本phpMyAdmin-4.0.7。面板数据库默认管理系统是由Amysql自主开发的AMS MySQL管理系统，建库建表查看修改删除数据、权限管理等能满足日常操作。部分功能目前还没有phpmyadmin强大，如另需使用phpmyadmin请安装。';
		echo 'AMH-ModuleButton: 安装/卸载';
		echo 'AMH-ModuleDate: 2013-09-29';
		echo 'AMH-ModuleAdmin: ./phpmyadmin407_amh/index.php';
		echo 'AMH-ModuleWebSite: http://nufeng.net';
		echo 'AMH-ModuleIco: http://amysql.com/View/images/amh_module/phpmyadmin.gif';
		echo 'AMH-ModuleScriptBy: 怒风';
}

#install
function amh_module_install()
{
		if amh_module_status ; then
				exit;
		else
				cd /usr/local/;
				wget http://code.amysql.com/files/phpMyAdmin-4.0.7-all-languages.zip;
				unzip phpMyAdmin-4.0.7-all-languages.zip;
				mv phpMyAdmin-4.0.7-all-languages /home/wwwroot/index/web/phpmyadmin407_amh;
				sed -i "/ams=index/a\<input type=\"button\" value=\"phpMyAdmin-4.0.7\" onclick=\"WindowOpen('./phpmyadmin407_amh/index.php');\"/>"  /home/wwwroot/index/web/View/mysql.php;
				amh_module_status;
		fi;
}

#admin
function amh_module_admin()
{
		if amh_module_status ; then
				echo '[OK] phpMyAdmin-4.0.7 Management:  http://ip:8888/phpmyadmin407_amh/ ';
		else
				exit;
		fi;
}

#uninstall
function amh_module_uninstall()
{
		if amh_module_status ; then

				rm -rf /home/wwwroot/index/web/phpmyadmin407_amh;
				rm -f /usr/local/phpMyAdmin-4.0.7-all-languages.zip;
				sed -i "/phpMyAdmin-4.0.7/d" /home/wwwroot/index/web/View/mysql.php;
				echo '[OK] phpMyAdmin-4.0.7 Uninstall successful.';
		else
				exit;
		fi;
}

#status
function amh_module_status()
{
		if [ -d "/home/wwwroot/index/web/phpmyadmin407_amh" ]; then
				echo '[OK] phpMyAdmin-4.0.7 is already installed.';
				return 0;
		else
				echo '[Notice] phpMyAdmin-4.0.7 is not installed.';
				return 1;
		fi;
}

