#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
		echo 'AMH-ModuleName: AMNetwork-1.0';
		echo 'AMH-ModuleDescription: AMNetwork - AMH面板网络管理模块，可在线配置防火墙规则、查看当前网络连接数据、当前网络通讯数据与当前系统运行程序进程。';
		echo 'AMH-ModuleButton: 安装/卸载';
		echo 'AMH-ModuleDate: 2013-10-04';
		echo 'AMH-ModuleAdmin: ./index.php?c=AMNetwork';
		echo 'AMH-ModuleWebSite: http://amysql.com';
		echo 'AMH-ModuleIco: http://amysql.com/View/images/amh_module/AMNetwork.gif';
		echo 'AMH-ModuleScriptBy: Amysql.';
}

#install
function amh_module_install()
{
		if amh_module_status ; then
			exit;
		else
			cd /root/amh/modules/AMNetwork-1.0;
			\cp ./Controller/AMNetwork.php  /home/wwwroot/index/web/Controller/;
			\cp ./View/{AMNetwork_category.php,AMNetwork_iptables.php,AMNetwork_netstat.php,AMNetwork_ps.php}  /home/wwwroot/index/web/View/;
			amh_module_status;
		fi;
}

#admin
function amh_module_admin()
{
		if amh_module_status ; then
			action=$1;
			[ "$action" == 'ps' ] && ps aux && exit 0;
			[ "$action" == 'netstat' ] && netstat -pan && exit 0;

			if [ "$action" == 'show_iptables' ]; then
				/sbin/iptables-save > /etc/amh-iptables;
				cat /etc/amh-iptables;
			fi;
			if [ "$action" == 'save_iptables' ]; then
				[ -f /tmp/amh-iptables ] && cat /tmp/amh-iptables >/etc/amh-iptables;
				/sbin/iptables-restore < /etc/amh-iptables;
			fi;

		else
			exit;
		fi;
}

#uninstall
function amh_module_uninstall()
{
		if amh_module_status ; then
			rm -f /home/wwwroot/index/web/Controller/AMNetwork.php /home/wwwroot/index/web/View/{AMNetwork_category.php,AMNetwork_iptables.php,AMNetwork_netstat.php,AMNetwork_ps.php};
			rm -f /tmp/amh-iptables;
			echo '[OK] AMNetwork Uninstall successful.';
		else
			exit;
		fi;
}

#status
function amh_module_status()
{
		if [ -f "/home/wwwroot/index/web/Controller/AMNetwork.php" ]; then
			echo '[OK] AMNetwork is already installed.';
			return 0;
		else
			echo '[Notice] AMNetwork is not installed.';
			return 1;
		fi;
}
